name: afs_task
description: A simple task manager app made as part of the technical interview for ADS.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_native_splash: ^2.2.19
  flutter_launcher_icons: ^0.12.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.0
  build_runner: ^2.3.3

flutter_icons:
  android: "launcher_icon"
  ios:
    generate: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/logo.png
  android_12:
    icon_background_color: "#ffffff"

  web: false

flutter:
  uses-material-design: true

  assets:
    - assets/images/
